apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |          # main config file
    global:
      scrape_interval: 5s    # pull metrics every 5 seconds

    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
      - targets: ['cadvisor.kube-system.svc.cluster.local:8080']

    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter.kube-system.svc.cluster.local:9100']